# -*- coding: utf-8 -*-
"""datafetch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oQ3Qltsd1cCY7myxaswY-psAM3zgrRXS
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import h5py
import os



def fetch_subject(subject_id):
  fileroot = 'drive/My Drive/bcic'
  subject_index = [i for i in range(1,16)]
  data = {}
  filepath = os.path.join(fileroot,'subj_{}.mat'.format(subject_index[subject_id]))
  f = h5py.File(filepath)
  for k, v in f.items():
    data[k] = np.array(v)
  return data

#data = fetch_subject(1)

#data.keys()

